// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using Microsoft.Extensions.Options;
using LMSV1.Data;
using LMSV1.Models;
using LMSV1.Pages;
using LMSV1.Pages.Courses.Assignments.Submissions;
using LMSV1.Pages.Courses.Student;

namespace UItest
{
    [TestFixture]
    public class TestInstructor1Test
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            //driver = new ChromeDriver();
            ChromeOptions options = new ChromeOptions();
            options.BinaryLocation = ("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe");
            driver = new ChromeDriver(options);
            driver.Manage().Window.Maximize();

            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void testInstructor1()
        {

            driver.Navigate().GoToUrl("https://localhost:7019");//5173
            Thread.Sleep(2000);
            driver.FindElement(By.Id("login")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("Instructor1@gmail.com");
            driver.FindElement(By.Id("Input_Password")).SendKeys("Abc123!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Manage Courses")).Click();
            driver.FindElement(By.LinkText("Add Course")).Click();
            driver.FindElement(By.Id("Input_DepartmentID")).Click();
            {
                var dropdown = driver.FindElement(By.Id("Input_DepartmentID"));
                dropdown.FindElement(By.XPath("//option[. = 'Computer Science']")).Click();
            }
            driver.FindElement(By.Id("Input_CourseID")).Click();
            driver.FindElement(By.Id("Input_CourseID")).SendKeys("1550");
            driver.FindElement(By.Id("Input_Title")).Click();
            driver.FindElement(By.Id("Input_Title")).SendKeys("Circuit and Relays");
            driver.FindElement(By.Id("Input_Credits")).Click();
            driver.FindElement(By.Id("Input_Credits")).SendKeys("4");
            driver.FindElement(By.Id("Input_Location")).Click();
            driver.FindElement(By.Id("Input_Location")).SendKeys("NB 120");
            driver.FindElement(By.Name("SelectedDays")).Click();
            driver.FindElement(By.CssSelector(".form-group > div > input:nth-child(2)")).Click();
            driver.FindElement(By.CssSelector("input:nth-child(4)")).Click();
            driver.FindElement(By.Id("Input_StartTime")).Click();
            driver.FindElement(By.Id("Input_StartTime")).Click();
            driver.FindElement(By.Id("Input_StartTime")).SendKeys("09:00");
            driver.FindElement(By.Id("Input_EndTime")).Click();
            driver.FindElement(By.Id("Input_EndTime")).Click();
            driver.FindElement(By.Id("Input_EndTime")).SendKeys("10:45");
            driver.FindElement(By.Id("Input_EndTime")).Click();
            driver.FindElement(By.CssSelector(".form-group:nth-child(9)")).Click();
            driver.FindElement(By.CssSelector(".btn-primary")).Click();
            driver.FindElement(By.LinkText("Delete")).Click();
            driver.FindElement(By.CssSelector(".btn-danger")).Click();
            driver.FindElement(By.Id("logout")).Click();
            driver.Close();
        }
    }
}