// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using Microsoft.Extensions.Options;
using LMSV1.Data;
using LMSV1.Models;
using LMSV1.Pages;
using LMSV1.Pages.Courses.Assignments.Submissions;
using LMSV1.Pages.Courses.Student;
using NuGet.ContentModel;

namespace UItest
{
    [TestFixture]
    public class TestInstructor1Test
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            //driver = new ChromeDriver();
            ChromeOptions options = new ChromeOptions();
            options.BinaryLocation = ("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe");
            driver = new ChromeDriver(options);
            driver.Manage().Window.Maximize();

            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void testInstructor1()
        {
            driver.Navigate().GoToUrl("https://localhost:7019");//5173
            Thread.Sleep(2000);
            driver.FindElement(By.Id("login")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("Instructor1@gmail.com");
            driver.FindElement(By.Id("Input_Password")).SendKeys("Abc123!");
            driver.FindElement(By.Id("login-submit")).Click();
            driver.FindElement(By.LinkText("Manage Courses")).Click();
            driver.FindElement(By.LinkText("Add Course")).Click();
            driver.FindElement(By.Id("Input_DepartmentID")).Click();
            {
                var dropdown = driver.FindElement(By.Id("Input_DepartmentID"));
                dropdown.FindElement(By.XPath("//option[. = 'Computer Science']")).Click();
            }
            driver.FindElement(By.Id("Input_CourseID")).Click();
            driver.FindElement(By.Id("Input_CourseID")).SendKeys("1550");
            driver.FindElement(By.Id("Input_Title")).Click();
            driver.FindElement(By.Id("Input_Title")).SendKeys("Circuit and Relays");
            driver.FindElement(By.Id("Input_Credits")).Click();
            driver.FindElement(By.Id("Input_Credits")).SendKeys("4");
            driver.FindElement(By.Id("Input_Location")).Click();
            driver.FindElement(By.Id("Input_Location")).SendKeys("NB 120");
            driver.FindElement(By.Name("SelectedDays")).Click();
            driver.FindElement(By.CssSelector(".form-group > div > input:nth-child(2)")).Click();
            driver.FindElement(By.CssSelector("input:nth-child(4)")).Click();
            driver.FindElement(By.Id("Input_StartTime")).Click();
            driver.FindElement(By.Id("Input_StartTime")).Click();
            driver.FindElement(By.Id("Input_StartTime")).SendKeys("09:00a");
            driver.FindElement(By.Id("Input_EndTime")).Click();
            driver.FindElement(By.Id("Input_EndTime")).Click();
            driver.FindElement(By.Id("Input_EndTime")).SendKeys("10:45a");
            driver.FindElement(By.Id("Input_EndTime")).Click();
            Thread.Sleep(10000);
            driver.FindElement(By.CssSelector(".form-group:nth-child(9)")).Click();
            driver.FindElement(By.CssSelector(".btn-primary")).Click();
            string courseName = "Circuit and Relays";
            var deleteLinkXPath = $"//table[@class='table']//tr[td[contains(text(), '{courseName}')]]//a[text()='Delete']";
            var deleteLink = driver.FindElement(By.XPath(deleteLinkXPath));
            Thread.Sleep(10000);
            deleteLink.Click();
            driver.FindElement(By.CssSelector(".btn-danger")).Click();
            driver.FindElement(By.Id("logout")).Click();
            driver.Close();
        }

        [Test]
        public void UITest_StudentRegistersForClass()
        {
            driver.Navigate().GoToUrl("https://localhost:7019");
            Thread.Sleep(2000);

            // Login
            driver.FindElement(By.Id("login")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("Student1@gmail.com");
            driver.FindElement(By.Id("Input_Password")).SendKeys("Abc123!");
            driver.FindElement(By.Id("login-submit")).Click();
            Thread.Sleep(2000);

            // Navigate to Course Registration
            driver.FindElement(By.LinkText("Course Registration")).Click();
            Thread.Sleep(2000);

            // Select a specific course and register
            string courseTitle = "Linear Algebra";
            var registerButtonXPath = $"//table[@class='table']//tr[td[contains(text(), '{courseTitle}')]]//input[@value='Register']";
            var registerButton = driver.FindElement(By.XPath(registerButtonXPath));
            registerButton.Click();
            Thread.Sleep(2000);

            // Validate successful registration
            // Navigate back to Dashboard
            driver.FindElement(By.LinkText("Dashboard")).Click();
            Thread.Sleep(2000);

            // Undo changes and logout
            driver.FindElement(By.LinkText("Course Registration")).Click();
            Thread.Sleep(2000);
            var dropButtonXPath = $"//table[@class='table']//tr[td[contains(text(), '{courseTitle}')]]//input[@value='Drop']";
            var dropButton = driver.FindElement(By.XPath(dropButtonXPath));
            dropButton.Click();
            Thread.Sleep(2000);
            driver.FindElement(By.Id("logout")).Click();
            Thread.Sleep(2000);

            // Close the browser
            driver.Close();
        }

        [Test]
        public void UITest_Instructor1GradesStudent1Assignment1()
        {
            driver.Navigate().GoToUrl("https://localhost:7019");
            Thread.Sleep(2000);

            // Login
            driver.FindElement(By.Id("login")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("Instructor1@gmail.com");
            driver.FindElement(By.Id("Input_Password")).SendKeys("Abc123!");
            driver.FindElement(By.Id("login-submit")).Click();
            Thread.Sleep(2000);

            // Navigate to Course home page for CS 3750
            driver.Navigate().GoToUrl("https://localhost:7019/Courses/CourseHome/3750");
            Thread.Sleep(2000);

            // Navigate to Assignment 1 submission for course CS 3750
            driver.Navigate().GoToUrl("https://localhost:7019/Courses/Assignments/Submissions/Submissions/1?cid=3750");
            Thread.Sleep(2000);

            // Navigate to Assignment 1 submission Grade for course CS 3750
            driver.Navigate().GoToUrl("https://localhost:7019/Courses/Assignments/Submissions/Grade?id=1&assId=1&cId=3750");
            Thread.Sleep(2000);
            
            // Grade the assignment to 100 and click save
            string courseTitle = "Linear Algebra";
            driver.FindElement(By.Name("score")).SendKeys("100");
            driver.FindElement(By.ClassName("btn-primary")).Click();
            Thread.Sleep(2000);

            //logout

            Thread.Sleep(2000);
            driver.FindElement(By.Id("logout")).Click();
            Thread.Sleep(2000);

            // Close the browser
            driver.Close();
        }
        //UI test added by Quinn
        [Test]
        public void InstructorCreatesAnAssignment()
        {
            //Go to the website
            driver.Navigate().GoToUrl("https://localhost:7019"); //5173
            Thread.Sleep(2000);

            //Login as the instructor
            driver.FindElement(By.Id("login")).Click();
            driver.FindElement(By.Id("Input_Email")).SendKeys("Instructor1@gmail.com");
            driver.FindElement(By.Id("Input_Password")).SendKeys("Abc123!");
            driver.FindElement(By.Id("login-submit")).Click();
            Thread.Sleep(2000);

            //Go to the specific course and create a new assingment
            driver.FindElement(By.LinkText("CS 3750")).Click();
            driver.FindElement(By.LinkText("Create new assignment")).Click();
            Thread.Sleep(2000);

            //Enter the data into the various fields
            driver.FindElement(By.Id("Input_Title")).Click();
            driver.FindElement(By.Id("Input_Title")).SendKeys("Syllabus Quiz");
            driver.FindElement(By.Id("Input_Description")).Click();
            driver.FindElement(By.Id("Input_Description")).SendKeys("Describe the Syllabus");
            driver.FindElement(By.Id("Input_MaxPoints")).Click();
            driver.FindElement(By.Id("Input_MaxPoints")).SendKeys("100");
            driver.FindElement(By.Id("Input_DueDate")).Click();
            driver.FindElement(By.Id("Input_DueDate")).SendKeys("121200202411301");
            driver.FindElement(By.Id("Input_SubmissionType")).Click();
            {
                var dropdown = driver.FindElement(By.Id("Input_SubmissionType"));
                dropdown.FindElement(By.XPath("//option[. = 'Text Entry']")).Click();
            }
            Thread.Sleep(2000);

            //Submit the creation
            driver.FindElement(By.LinkText("Create")).Click();
            driver.FindElement(By.LinkText("Dashboard")).Click();
            Thread.Sleep(2000);

            //Go confirm the assignment is created
            driver.FindElement(By.LinkText("CS 3750")).Click();
            driver.FindElement(By.LinkText("Syllabus Quiz")).Click();
            Thread.Sleep(5000);

            //Logout of the system
            driver.FindElement(By.Id("logout")).Click();
            driver.Close();
        }
}   
}

